# rules.toml
[frontends]
    [frontends.dui]
        backend = "dui"
        passHostHeader = true
        entrypoints = ["https"]
        [frontends.dui.routes]
            [frontends.dui.routes.route]
            rule = "Host:dui.home.m3"

[backends]
    [backends.dui]
        [backends.dui.LoadBalancer]
            method = "drr"
            [backends.dui.loadbalancer.stickiness]
        [backends.dui.servers] 
            [backends.dui.servers.server1]
            url = "http://127.0.0.1:5000"
            weight = 1
##