version: "3.6"

services:
  dui:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dhnt/dui:latest
    restart: always
    container_name: dui
    hostname: dui
    ports:
      - "5000:5000"
    # working_dir: /opt/docker-compose/
    # environment:
    #   - 'WEB_CONSOLE_PATTERN=/web-console/?cid={containerName}&cmd={command}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #   - ./:/opt/docker-compose
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend=dui"
      - "traefik.docker.network=web"
      - "traefik.entrypoints=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:dui.home"
      - "traefik.port=5000"

networks:
  web:
    external: false
    name: web
